# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 8
    - run: npm install -g appium
    - name: Prepare iPhone SE (2nd generation) simulator
      run: |
        sudo mkdir -p /Library/Developer/CoreSimulator/Profiles/Runtimes
        sudo ln -s /Applications/Xcode_12.4.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/CoreSimulator/Profiles/Runtimes/iOS.simruntime /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS\ 14.4.simruntime
        xcrun simctl list runtimes
        xcrun simctl create custom-test-device "iPhone SE (2nd generation)" "com.apple.CoreSimulator.SimRuntime.iOS-14-4"
        xcrun simctl list devices 14.4
    - name: Build with Maven
      run: mvn -B clean test --file pom.xml