# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 8
    - run: npm install -g appium
    - name: prepare emulator
      uses: reactivecircus/android-emulator-runner@v2
      with: 
        arch: x86_64
        api-level: 29
        profile: pixel_3
        script: ./gradlew connectedCheck
    - name: Build with Maven
      run: mvn -B clean test --file pom.xml
