# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 8
    - run: npm install -g appium
    - name: Prepare iPhone SE (2nd generation) simulator
      uses: futureware-tech/simulator-action@v1
      with:
        model: 'iPhone SE (2nd generation)'
        os_version: 14.4
    - name: Build with Maven
      run: mvn -B clean test --file pom.xml